<a href="https://colab.research.google.com/github/ManishKr19/Innomatics-Research-Labs/blob/main/Task_6_(Numpy_Both_for_Basic_and_Adv_User).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Task - 6 (Numpy - Both for Basic and Adv User)**



[https://www.hackerrank.com/domains/python?filters%5Bsubdomains%5D%5B%5D=numpy]( https://www.hackerrank.com/domains/python?filters%5Bsubdomains%5D%5B%5D=numpy)

***Arrays***

In [ ]:
import numpy
def arrays(arr):
    arr = [float(it) for it in arr]
    return numpy.array(arr[::-1])

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


***Shape and Reshape***

In [1]:
import numpy as np
lst = list(map(int, input().split()))
arr = np.array(lst)
print(arr.reshape(3,3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


***Transpose and Flatten***

In [2]:
import numpy as np
arr = np.array([input().split() for y in range(int(input().split()[0] ))], int)
print(np.transpose(arr), arr.flatten(), sep="\n")


2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


***Cocatenate***

In [3]:
import numpy as np
N,M,P = map(int, input().split())
arr = np.array([input().split() for y in range(N)], int)

arr1 = np.array([input().split() for y in range(M)], int)

print(np.concatenate((arr,arr1), axis=0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


***Zeros and Ones***

In [5]:
import numpy as np
tup = tuple(map(int, input().split()))
print(np.zeros(tup, dtype=np.int64))
print(np.ones(tup,dtype=np.int64))


3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


***Eye and Identity***

In [7]:
import numpy as np
n,m = map(int, input().split())
np.set_printoptions(sign=' ')
print(np.eye(n,m))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


***Array Mathematics***

In [8]:
import numpy as np
n,m = map(int,input().split())

a=np.zeros((n,m),int)
b=np.zeros((n,m),int)
for i in range(n):
  a[i]=np.array(input().split(),int)
for i in range(n):
  b[i]=np.array(input().split(),int)  

print(a+b)
print(a-b)
print(a*b)
print(np.array(a/b,int))
print(a%b)
print(a**b)

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


***Floor, Ceil and Rint***

In [9]:
import numpy as np
np.set_printoptions(legacy = '1.13')
ar = np.array(input().strip().split(), float)
print(np.floor(ar), np.ceil(ar), np.rint(ar), sep = "\n")

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


***Sum and Prod***

In [12]:
import numpy as np
print(np.prod(np.sum(np.array([input().split() for _ in range(int(input().split()[0])) ],int),axis=0)))

2 2
1 2
3 4
24


***Min and Max***

In [13]:
import numpy as np
N,M = map(int, input().split())
arr = np.array([input().split() for y in range(N)], int)

print(np.max(np.min(arr, axis=1)))

2 2
1 2
3 4
3


***Mean, Var, and Std***

In [14]:
import numpy

nm = input().split()
n = int(nm[0])
m = int(nm[1])
arr = []
for i in range(n):
    m = list(map(int, input().split()))
    arr.append(m)
arr = numpy.array(arr)

mean = numpy.mean(arr, axis = 1)
var = numpy.var(arr, axis = 0)
std = numpy.std(arr)

print(mean)
print(var)

rnd = numpy.around(std, 11)
print(rnd)

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


***Dot and Cross***

In [15]:
import numpy
n = int(input())
a = numpy.array([input().split() for _ in range(n)], int)
b = numpy.array([input().split() for _ in range(n)], int)
print(numpy.dot(a, b))

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


***Inner and Outer***

In [1]:
import numpy as np
A = np.array(input().split(), int)
B = np.array(input().split(), int)
print(np.inner(A,B), np.outer(A,B), sep='\n')

0 1
2 3
3
[[0 0]
 [2 3]]


***Polynomials***

In [2]:
print(__import__('numpy').polyval(list(map(float,input().split())),float(input())))

1.1 2 3
0
3.0


***Linear Algebra***

In [3]:
import numpy
print(round(numpy.linalg.det(numpy.array([list(map(float,input().split())) for _ in range(int(input()))])),2))

2
1.1 1.1
1.1 1.1
0.0
